---
fullname: Continuous Fraction
shortname: cfrac
organization: thery
community: false
dune: false
action: true

synopsis: Continuous Fraction in Coq

description: |-
  Continuous Fraction in Coq

authors:
- name: Laurent Théry

maintainers:
- name: Laurent Théry
  nickname: thery

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: '8.18 or later'
  opam: '{(>= "8.18")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "2.2.0")}'
  description: |-
    [MathComp ssreflect 2.2 or later](https://math-comp.github.io)

tested_coq_opam_versions:
- version: '2.2.0-coq-8.18'
  repo: 'mathcomp/mathcomp'

namespace: cfrac

keywords:
- name: continuous fraction


---