---
fullname: Continuous Fraction
shortname: cfrac
organization: thery
community: false
dune: false
action: true

synopsis: Continuous Fraction in Rocq

description: |-
  Continuous Fraction in RocqS

authors:
- name: Laurent Théry

maintainers:
- name: Laurent Théry
  nickname: thery

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_rocq_versions:
  text: '9.1 or later'
  opam: '{(>= "9.1")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "2.5.0")}'
  description: |-
    [MathComp ssreflect 2.5 or later](https://math-comp.github.io)

tested_coq_opam_versions:
- version: '2.5.0-rocq-prover-9.1'
  repo: 'mathcomp/mathcomp'

namespace: cfrac

keywords:
- name: continuous fraction


---