---
fullname: Continuous Fraction
shortname: cfrac
organization: thery
community: false
dune: false
action: true

synopsis: Continuous Fraction in Coq

description: |-
  Continuous Fraction in Coq

authors:
- name: Laurent Théry

maintainers:
- name: Laurent Théry
  nickname: thery

opam-file-maintainer: thery@sophia.inria.fr

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: '8.20 or later'
  opam: '{(>= "8.20")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "2.4.0")}'
  description: |-
    [MathComp ssreflect 2.4 or later](https://math-comp.github.io)
- opam:
    name: conf-csdp
    version: '{(>= "1")}'
  description: |-
    Virtual package relying on a CSDP binary system installation

tested_coq_opam_versions:
- version: '2.4.0-coq-8.20'
  repo: 'mathcomp/mathcomp'

namespace: cfrac

keywords:
- name: continuous fraction


---